### ISSUE TITLE
KMP export path not working

### ISSUE THREAD

**Issue by MitjaHenner** [mikepenz/AboutLibraries#916] opened 2023-09-08 20:06 UTC
## About this issue
I'm using compose multiplatform and moko resources, I want to export the aboutLibraries.json to the moko folder, but when I run: `./gradlew common:exportLibraryDefinitions -PaboutLibraries.exportPath=src/commonMain/resources/MR/files/  ` 
I get:
`Task '.exportPath=src/commonMain/resources/MR/files/' not found in root project 'Project' and its subprojects.`

## Details
- [10.9.0-b02] Used library version
- [1.5.0] Compose
- [8.2 / 8.1.1 AGP] Used gradle build tools version
- [2023.1.1 Beta 3] Used tooling / Android Studio version

**Comment by mikepenz** [comment] 2023-09-22 14:04
@MitjaHenner this looks to be some form of problem with the way the `exportPath` is passed. 

Can you please provide more details of your environment? Can you reproduce this with this project itself using:

```
./gradlew app-desktop:exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/resources/
```

Tested it locally and it does not seem to have problems with it.

**Comment by mikepenz** [comment] 2023-10-13 10:26
Please report back. Closing due to in-activity

**Closed by mikepenz** 2023-10-13 10:26 UTC

**Comment by Faltenreich** [comment] 2024-09-23 17:52
I have the same problem using AboutLibraries 11.2.3 within [this KMP project](https://github.com/Faltenreich/Diaguard/tree/feature/multiplatform) when executing `./gradlew exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/resources/` on a Windows machine. Maybe there is something wrong with path separators on this operating system?

**Comment by Faltenreich** [comment] 2024-09-23 17:57
Update: I have found the solution.

Instead of 

```
./gradlew exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/resources/
```

I need to execute

```
./gradlew exportLibraryDefinitions -PexportPath=src/main/resources/
```

and the .json is generated as expected.

**Comment by mikepenz** [comment] 2024-09-24 06:32
are you by any chance on linux and not macOS? I believe I observed in the past that the `.` is not accepted on these systems. so `exportPath` is a fallback:

https://github.com/mikepenz/AboutLibraries/blob/e8a4fe3aa5b963205c986d1e0f768ca96ede3c86/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportComplianceTask.kt#L14

**Comment by Faltenreich** [comment] 2024-09-24 18:47
I am on Windows (11).

**Comment by mikepenz** [comment] 2024-09-25 06:13
@Faltenreich ah, seeing `./gradlew ...` I assumed it was unix. but yes windows is also handling `.`'s differently
