### ISSUE TITLE
GPL 3.0 license is not properly detected / mapped to their corresponding SPDX license

### ISSUE THREAD

**Issue by mbiebl** [mikepenz/AboutLibraries#892] opened 2023-06-19 17:01 UTC
Version: 10.7.0

When including a library that uses a GPL license, like GPL-3.0, this library is not properly detected.
In my particular case I want to include cert4android, which has the following pom file:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- do_not_remove: published-with-gradle-metadata -->
<modelVersion>4.0.0</modelVersion>
  <groupId>com.github.bitfireAT</groupId>
  <artifactId>cert4android</artifactId>
  <version>c87a7e9</version>
  <packaging>aar</packaging>
  <name>bitfireAT/cert4android</name>
  <description>Android service + TrustManager for managing custom certificates in an app-private key store</description>
  <url>https://github.com/bitfireAT/cert4android</url>
  <inceptionYear>2021</inceptionYear>
  <licenses>
    <license>
      <name>GNU General Public License v3.0</name>
      <url>https://api.github.com/licenses/gpl-3.0</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>bitfireAT</id>
      <name>bitfire web engineering</name>
      <email>play@bitfire.at</email>
    </developer>
  </developers>
  <scm>
    <connection>scm:git://github.com/bitfireAT/cert4android.git</connection>
    <developerConnection>scm:git://github.com/bitfireAT/cert4android.git</developerConnection>
    <url>git://github.com/bitfireAT/cert4android.git</url>
  </scm>
....
```

Yet, `./gradlew exportLibraries` says
```
...
LICENSES:
BSD-3-Clause;BSD 3-Clause "New" or "Revised" License;https://spdx.org/licenses/BSD-3-Clause.html
MIT;MIT License;https://spdx.org/licenses/MIT.html
BSD-2-Clause;BSD 2-Clause "Simplified" License;https://spdx.org/licenses/BSD-2-Clause.html
Apache-2.0;Apache License 2.0;https://spdx.org/licenses/Apache-2.0.html
EPL-1.0;Eclipse Public License 1.0;https://spdx.org/licenses/EPL-1.0.html
EPL-2.0;Eclipse Public License 2.0;https://spdx.org/licenses/EPL-2.0.html
MPL-2.0;Mozilla Public License 2.0;https://spdx.org/licenses/MPL-2.0.html


ARTIFACTS WITHOUT LICENSE:


UNKNOWN LICENSES:
GNU General Public License v3.0
-- [com.github.bitfireAT:cert4android:c87a7e9]
```

If you want to reproduce the problem, you can checkout https://github.com/mbiebl/AboutLibraries/tree/gpl-license
specifically https://github.com/mbiebl/AboutLibraries/commit/b7731d122ba9a0ae019326df9f9c3afcbb4c742b

If you open the AboutLibraries demo app, the Compose Activity doesn't show any license information for the cert4android library, or to be more specific: it shows the strings "GNU General Public License 3.0" but tapping on it doesn't open https://spdx.org/licenses/GPL-3.0-or-later.html or like in older versions an embedded version of the license text (as for example for Apache-2.0).

**Comment by mikepenz** [comment] 2023-06-19 18:50
The correct identifier is `GNU General Public License v3.0 only` (including `only`) - https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/SpdxLicense.kt#L178 

That's why it is not automatically detected.

**Comment by mbiebl** [comment] 2023-06-20 09:06
Hm, I vaguely remember that with v8 the GPL mapping worked and for the above library the GPL license information was shown. I'll double check.

**Comment by mbiebl** [comment] 2023-06-20 11:00
> Hm, I vaguely remember that with v8 the GPL mapping worked and for the above library the GPL license information was shown. I'll double check.

I misremembered. This didn't work with v8 either. So there is at least no regression.

**Comment by mikepenz** [comment] 2023-06-20 11:54
I believe this ticket can be closed in this case?

There's a different ticket open to upgrade to SPDX 2.0 identifiers at some point, however that may be a larger task, as that looks to have significantly changed the structure.

**Comment by mbiebl** [comment] 2023-06-20 12:01
> I believe this ticket can be closed in this case?

I guess so, unless you plan to add some clever heuristics how to map those licenses.

I will probably need to talk to the authors of cert4android, but I'm not sure there is actually anything that they can fix on their side. 
Might just be the way jitpack.io operates when pulling from github.

**Comment by mikepenz** [comment] 2023-06-20 12:13
Well we do have some heuristics to map some licenses. (not really clever though :D) 
The problem is, that I am not 100% certain that `GNU General Public License v3.0` is guaranteed to be equal to `GNU General Public License v3.0 only`.

If that's the case, then adding special handling like already done for these licenses makes sense: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/SpdxLicense.kt#L385-L406

Actually 🤔. there is something else we can probably do. Looks this library links to the license API from GitHub. 
We do already have handling to identify the license from GitHub via the repo link however detecting that the license itself links to GitHub may be a solution. 

As this links to the short-hand spdx identifier, which links to: https://spdx.org/licenses/GPL-3.0.html

------

Edit. following these, yes it looks `v3.0 only` is equal to `v3.0`. So the heuristic can also be done.

**Closed** 2023-06-23 15:07 UTC

**Comment by mbiebl** [comment] 2023-06-30 12:45
Hi, with the latest changes this looks better now:
```
exportLibraries 

...
bitfireAT/cert4android;com.github.bitfireAT:cert4android:c87a7e9;GPL-3.0-only
```

But in the (compose based) about dialog it shows

![image](https://github.com/mikepenz/AboutLibraries/assets/3609611/a01fd3ee-eb0d-4364-b616-92a5ce310f08)

and tapping on "GNU General Public License 3.0" does nothing.

**Comment by mikepenz** [comment] 2023-07-08 08:46
Thanks @mbiebl, I actually realised that I missed to enable that behaviour for Android targets, it would only happen for other platforms. Will be in the next update.
