### ISSUE TITLE
[WINDOWS] Question marks in owner/author

### ISSUE THREAD

**Issue by Nekromancer** [mikepenz/AboutLibraries#472] opened 2020-02-17 12:10 UTC
Using gradle plugin in 8.0.0-rc01 version i cannot build app. 

Build crashes with error:
```
C:\Projects\<redacted>\app\build\generated\aboutlibraries\res\values\aboutlibraries.xml:1707:3-67: AAPT: error: resource attr/?? (aka <redacted>:attr/??) not found.
```
Fragment of generated aboutlibraries.xml. Those 2 lines with `???` are giving me compile error
```
<string name="library_me_xuender__unidecode_author">???</string>
  <string name="library_me_xuender__unidecode_authorWebsite">http://xuender.me</string>
  <string name="library_me_xuender__unidecode_libraryName">unidecode</string>
  <string name="library_me_xuender__unidecode_libraryDescription"><![CDATA[ASCII transliterations of Unicode text for Java]]></string>
  <string name="library_me_xuender__unidecode_libraryVersion">0.0.7</string>
  <string name="library_me_xuender__unidecode_libraryArtifactId">me.xuender:unidecode:0.0.7</string>
  <string name="library_me_xuender__unidecode_libraryWebsite">https://github.com/xuender/unidecode</string>
  <string name="library_me_xuender__unidecode_licenseId">Apache_2_0</string>
  <string name="library_me_xuender__unidecode_isOpenSource">true</string>
  <string name="library_me_xuender__unidecode_repositoryLink">git@github.com:xuender/unidecode.git</string>
  <string name="library_me_xuender__unidecode_owner">???</string>
```

**Comment by mikepenz** [comment] 2020-02-17 12:19
@Nekromancer thanks for the report. Will have to see what the pom specifies for those texts. :/

**Comment by mikepenz** [comment] 2020-02-17 14:27
Hmmm it works perfectly fine on a mac :/

can you please look into the following file:

```
build/generated/aboutlibraries/res/values/aboutlibraries.xml
```

and see what is written there? Maybe the gradle build / build environment has issues with chinese characters?

if it is already broken at this state then we wrote it wrong, but if it is alright then the build may need to be configured to support UTF-8 (not sure though, got no windows to try with)

**Comment by koral--** [comment] 2020-02-17 15:02
`Hmmm it works perfectly fine on a mac :/`
It seems that your default encoding is set to something using UTF-8 unlike on the OP's machine.

@Nekromancer 
Is that issue reproducible if you invoke gradle task with `-Dfile.encoding=UTF-8` parameter?

**Comment by Nekromancer** [comment] 2020-02-18 07:05
I can confirm that this parameter fixes issue

**Comment by mikepenz** [comment] 2020-02-19 09:46
@koral-- any idea how this could be made default? 
I suppose this would be a general issue for all cases on android.

**Comment by koral--** [comment] 2020-02-19 17:16
It seems that somewhere in the code, when reading and/or writing some file, the encoding is not specified explicitly so default system encoding is used implicitly.
For example here: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin/src/main/groovy/com/mikepenz/aboutlibraries/plugin/AboutLibrariesTask.groovy#L52 `FileWriter` uses system-default encoding.

**Comment by mikepenz** [comment] 2020-02-19 17:17
ok let's see if it is fixed by adding in more places :)

**Comment by mikepenz** [comment] 2020-02-19 17:32
I hope this fixes the problem: https://github.com/mikepenz/AboutLibraries/commit/b31a5b537c32a57b75dc11cbfed7bbb4b25446b8 

`FileWriter` doesn't allow to provide the charset

**Comment by vitorhugods** [comment] 2020-02-27 15:52
I'm facing _probably_ the same issue. But I cannot reproduce it easily. 

```
resource attr/?? (aka <redacted>:attr/??) not found
```

During CI/CD pipelines, running Jenkins in a Linux machine.

**Comment by mikepenz** [comment] 2020-02-28 10:17
Released rc02 with the utf8 fix. Please let me know if things behave better now

@vitorhugods @Nekromancer

**Closed by mikepenz** 2020-02-28 10:17 UTC
Labels: bug, enhancement
