### ISSUE TITLE
error "Retrieved no components for:" after changing build.gradle to build.gradle.kts

### ISSUE THREAD

**Issue by tateisu** [mikepenz/AboutLibraries#931] opened 2023-10-10 04:22 UTC
```
com.mikepenz.aboutlibraries.plugin 
10.9.1

> Task :app:prepareLibraryDefinitionsXXX
--> Retrieved no components for: androidx.activity:activity:1.8.0
--> Retrieved no components for: androidx.activity:activity-ktx:1.8.0
--> Retrieved no components for: androidx.annotation:annotation-experimental:1.3.0
--> Retrieved no components for: androidx.annotation:annotation-jvm:1.7.0
--> Retrieved no components for: androidx.appcompat:appcompat:1.6.1
--> Retrieved no components for: androidx.appcompat:appcompat-resources:1.6.1
--> Retrieved no components for: androidx.arch.core:core-common:2.2.0
--> Retrieved no components for: androidx.arch.core:core-runtime:2.2.0
--> Retrieved no components for: androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
--> Retrieved no components for: androidx.browser:browser:1.6.0
--> Retrieved no components for: androidx.cardview:cardview:1.0.0
--> Retrieved no components for: androidx.collection:collection:1.2.0
--> Retrieved no components for: androidx.collection:collection-ktx:1.1.0
--> Retrieved no components for: androidx.concurrent:concurrent-futures:1.1.0
--> Retrieved no components for: androidx.constraintlayout:constraintlayout:2.1.4
--> Retrieved no components for: androidx.constraintlayout:constraintlayout-core:1.0.4
--> Retrieved no components for: androidx.coordinatorlayout:coordinatorlayout:1.1.0
--> Retrieved no components for: androidx.core:core:1.9.0
--> Retrieved no components for: androidx.core:core-ktx:1.9.0
--> Retrieved no components for: androidx.cursoradapter:cursoradapter:1.0.0
--> Retrieved no components for: androidx.customview:customview:1.1.0
--> Retrieved no components for: androidx.customview:customview-poolingcontainer:1.0.0
--> Retrieved no components for: androidx.databinding:databinding-adapters:8.1.0
--> Retrieved no components for: androidx.databinding:databinding-common:8.1.0
--> Retrieved no components for: androidx.databinding:databinding-ktx:8.1.0
--> Retrieved no components for: androidx.databinding:databinding-runtime:8.1.0
--> Retrieved no components for: androidx.databinding:viewbinding:8.1.0
--> Retrieved no components for: androidx.datastore:datastore:1.0.0
--> Retrieved no components for: androidx.datastore:datastore-core:1.0.0
--> Retrieved no components for: androidx.datastore:datastore-preferences:1.0.0
--> Retrieved no components for: androidx.datastore:datastore-preferences-core:1.0.0
--> Retrieved no components for: androidx.documentfile:documentfile:1.0.0
--> Retrieved no components for: androidx.drawerlayout:drawerlayout:1.1.1
--> Retrieved no components for: androidx.dynamicanimation:dynamicanimation:1.0.0
--> Retrieved no components for: androidx.emoji2:emoji2:1.4.0
--> Retrieved no components for: androidx.emoji2:emoji2-bundled:1.4.0
--> Retrieved no components for: androidx.emoji2:emoji2-views-helper:1.4.0
--> Retrieved no components for: androidx.exifinterface:exifinterface:1.3.6
--> Retrieved no components for: androidx.fragment:fragment:1.6.0
--> Retrieved no components for: androidx.fragment:fragment-ktx:1.6.0
--> Retrieved no components for: androidx.gridlayout:gridlayout:1.0.0
--> Retrieved no components for: androidx.interpolator:interpolator:1.0.0
--> Retrieved no components for: androidx.legacy:legacy-support-core-ui:1.0.0
--> Retrieved no components for: androidx.legacy:legacy-support-core-utils:1.0.0
--> Retrieved no components for: androidx.legacy:legacy-support-v4:1.0.0
--> Retrieved no components for: androidx.lifecycle:lifecycle-common:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-common-java8:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-extensions:2.2.0
--> Retrieved no components for: androidx.lifecycle:lifecycle-livedata:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-livedata-core:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-livedata-core-ktx:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-livedata-ktx:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-process:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-reactivestreams:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-reactivestreams-ktx:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-runtime:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-runtime-ktx:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-service:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-viewmodel:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2
--> Retrieved no components for: androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2
--> Retrieved no components for: androidx.loader:loader:1.0.0
--> Retrieved no components for: androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
--> Retrieved no components for: androidx.media3:media3-common:1.1.1
--> Retrieved no components for: androidx.media3:media3-container:1.1.1
--> Retrieved no components for: androidx.media3:media3-database:1.1.1
--> Retrieved no components for: androidx.media3:media3-datasource:1.1.1
--> Retrieved no components for: androidx.media3:media3-decoder:1.1.1
--> Retrieved no components for: androidx.media3:media3-effect:1.1.1
--> Retrieved no components for: androidx.media3:media3-exoplayer:1.1.1
--> Retrieved no components for: androidx.media3:media3-exoplayer-dash:1.1.1
--> Retrieved no components for: androidx.media3:media3-exoplayer-hls:1.1.1
--> Retrieved no components for: androidx.media3:media3-extractor:1.1.1
--> Retrieved no components for: androidx.media3:media3-muxer:1.1.1
--> Retrieved no components for: androidx.media3:media3-session:1.1.1
--> Retrieved no components for: androidx.media3:media3-transformer:1.1.1
--> Retrieved no components for: androidx.media3:media3-ui:1.1.1
--> Retrieved no components for: androidx.media:media:1.6.0
--> Retrieved no components for: androidx.multidex:multidex:2.0.1
--> Retrieved no components for: androidx.navigation:navigation-common:2.7.4
--> Retrieved no components for: androidx.navigation:navigation-common-ktx:2.7.4
--> Retrieved no components for: androidx.navigation:navigation-fragment:2.7.4
--> Retrieved no components for: androidx.navigation:navigation-fragment-ktx:2.7.4
--> Retrieved no components for: androidx.navigation:navigation-runtime:2.7.4
--> Retrieved no components for: androidx.navigation:navigation-runtime-ktx:2.7.4
--> Retrieved no components for: androidx.navigation:navigation-ui:2.7.4
--> Retrieved no components for: androidx.navigation:navigation-ui-ktx:2.7.4
--> Retrieved no components for: androidx.preference:preference:1.2.1
--> Retrieved no components for: androidx.preference:preference-ktx:1.2.1
--> Retrieved no components for: androidx.print:print:1.0.0
--> Retrieved no components for: androidx.profileinstaller:profileinstaller:1.3.0
--> Retrieved no components for: androidx.recyclerview:recyclerview:1.3.1
--> Retrieved no components for: androidx.resourceinspection:resourceinspection-annotation:1.0.1
--> Retrieved no components for: androidx.room:room-common:2.5.2
--> Retrieved no components for: androidx.room:room-ktx:2.5.2
--> Retrieved no components for: androidx.room:room-runtime:2.5.2
--> Retrieved no components for: androidx.savedstate:savedstate:1.2.1
--> Retrieved no components for: androidx.savedstate:savedstate-ktx:1.2.1
--> Retrieved no components for: androidx.slidingpanelayout:slidingpanelayout:1.2.0
--> Retrieved no components for: androidx.sqlite:sqlite:2.3.1
--> Retrieved no components for: androidx.sqlite:sqlite-framework:2.3.1
--> Retrieved no components for: androidx.sqlite:sqlite-ktx:2.3.1
--> Retrieved no components for: androidx.startup:startup-runtime:1.1.1
--> Retrieved no components for: androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
--> Retrieved no components for: androidx.tracing:tracing:1.0.0
--> Retrieved no components for: androidx.transition:transition:1.4.1
--> Retrieved no components for: androidx.vectordrawable:vectordrawable:1.1.0
--> Retrieved no components for: androidx.vectordrawable:vectordrawable-animated:1.1.0
--> Retrieved no components for: androidx.versionedparcelable:versionedparcelable:1.1.1
--> Retrieved no components for: androidx.viewpager2:viewpager2:1.1.0-beta02
--> Retrieved no components for: androidx.viewpager:viewpager:1.0.0
--> Retrieved no components for: androidx.window:window:1.0.0
--> Retrieved no components for: androidx.work:work-runtime:2.8.1
--> Retrieved no components for: androidx.work:work-runtime-ktx:2.8.1
--> Retrieved no components for: androidx.work:work-testing:2.8.1
--> Retrieved no components for: com.airbnb.android:lottie:5.2.0
--> Retrieved no components for: com.amazonaws:aws-android-sdk-auth-core:2.25.0
--> Retrieved no components for: com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.25.0
--> Retrieved no components for: com.amazonaws:aws-android-sdk-cognitoidentityprovider-asf:1.0.0
--> Retrieved no components for: com.amazonaws:aws-android-sdk-core:2.25.0
--> Retrieved no components for: com.amazonaws:aws-android-sdk-iot:2.25.0
--> Retrieved no components for: com.amazonaws:aws-android-sdk-mobile-client:2.25.0
--> Retrieved no components for: com.android.volley:volley:1.2.1
--> Retrieved no components for: com.getkeepsafe.relinker:relinker:1.4.3
--> Retrieved no components for: com.github.akarnokd:rxjava3-retrofit-adapter:3.0.0
--> Retrieved no components for: com.github.barteksc:android-pdf-viewer:3.2.0-beta.1
--> Retrieved no components for: com.github.barteksc:pdfium-android:1.9.0
--> Retrieved no components for: com.github.bumptech.glide:annotations:4.15.1
--> Retrieved no components for: com.github.bumptech.glide:disklrucache:4.15.1
--> Retrieved no components for: com.github.bumptech.glide:gifdecoder:4.15.1
--> Retrieved no components for: com.github.bumptech.glide:glide:4.15.1
--> Retrieved no components for: com.github.bumptech.glide:okhttp3-integration:4.15.1
--> Retrieved no components for: com.github.chrisbanes:PhotoView:2.3.0
--> Retrieved no components for: com.github.hadilq:live-event:1.3.0
--> Retrieved no components for: com.github.ksoichiro:android-observablescrollview:1.5.0
--> Retrieved no components for: com.github.lisawray.groupie:groupie:2.8.0
--> Retrieved no components for: com.github.lisawray.groupie:groupie-viewbinding:2.8.0
--> Retrieved no components for: com.github.omadahealth:swipy:1.2.3
--> Retrieved no components for: com.google.android.datatransport:transport-api:3.0.0
--> Retrieved no components for: com.google.android.datatransport:transport-backend-cct:3.1.9
--> Retrieved no components for: com.google.android.datatransport:transport-runtime:3.1.9
--> Retrieved no components for: com.google.android.flexbox:flexbox:3.0.0
--> Retrieved no components for: com.google.android.gms:play-services-ads-identifier:18.0.0
--> Retrieved no components for: com.google.android.gms:play-services-auth:20.7.0
--> Retrieved no components for: com.google.android.gms:play-services-auth-api-phone:18.0.1
--> Retrieved no components for: com.google.android.gms:play-services-auth-base:18.0.4
--> Retrieved no components for: com.google.android.gms:play-services-base:18.0.1
--> Retrieved no components for: com.google.android.gms:play-services-basement:18.2.0
--> Retrieved no components for: com.google.android.gms:play-services-cloud-messaging:17.0.1
--> Retrieved no components for: com.google.android.gms:play-services-fido:20.0.1
--> Retrieved no components for: com.google.android.gms:play-services-measurement:21.3.0
--> Retrieved no components for: com.google.android.gms:play-services-measurement-api:21.3.0
--> Retrieved no components for: com.google.android.gms:play-services-measurement-base:21.3.0
--> Retrieved no components for: com.google.android.gms:play-services-measurement-impl:21.3.0
--> Retrieved no components for: com.google.android.gms:play-services-measurement-sdk:21.3.0
--> Retrieved no components for: com.google.android.gms:play-services-measurement-sdk-api:21.3.0
--> Retrieved no components for: com.google.android.gms:play-services-stats:17.0.2
--> Retrieved no components for: com.google.android.gms:play-services-tasks:18.0.2
--> Retrieved no components for: com.google.android.material:material:1.10.0
--> Retrieved no components for: com.google.code.findbugs:jsr305:3.0.2
--> Retrieved no components for: com.google.code.gson:gson:2.9.1
--> Retrieved no components for: com.google.errorprone:error_prone_annotations:2.15.0
--> Retrieved no components for: com.google.firebase:firebase-analytics:21.3.0
--> Retrieved no components for: com.google.firebase:firebase-annotations:16.2.0
--> Retrieved no components for: com.google.firebase:firebase-common:20.3.3
--> Retrieved no components for: com.google.firebase:firebase-common-ktx:20.3.3
--> Retrieved no components for: com.google.firebase:firebase-components:17.1.0
--> Retrieved no components for: com.google.firebase:firebase-crashlytics:18.4.3
--> Retrieved no components for: com.google.firebase:firebase-datatransport:18.1.8
--> Retrieved no components for: com.google.firebase:firebase-encoders:17.0.0
--> Retrieved no components for: com.google.firebase:firebase-encoders-json:18.0.1
--> Retrieved no components for: com.google.firebase:firebase-encoders-proto:16.0.0
--> Retrieved no components for: com.google.firebase:firebase-iid-interop:17.1.0
--> Retrieved no components for: com.google.firebase:firebase-installations:17.1.3
--> Retrieved no components for: com.google.firebase:firebase-installations-interop:17.1.0
--> Retrieved no components for: com.google.firebase:firebase-measurement-connector:19.0.0
--> Retrieved no components for: com.google.firebase:firebase-messaging:23.2.1
--> Retrieved no components for: com.google.firebase:firebase-sessions:1.0.2
--> Retrieved no components for: com.google.guava:failureaccess:1.0.1
--> Retrieved no components for: com.google.guava:guava:31.1-android
--> Retrieved no components for: com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
--> Retrieved no components for: com.ibm.icu:icu4j:71.1
--> Retrieved no components for: com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0
--> Retrieved no components for: com.jakewharton.timber:timber:5.0.1
--> Retrieved no components for: com.makeramen:roundedimageview:1.5.0
--> Retrieved no components for: com.mikepenz:aboutlibraries-core-android-debug:10.9.1
--> Retrieved no components for: com.squareup.moshi:moshi:1.14.0
--> Retrieved no components for: com.squareup.moshi:moshi-adapters:1.14.0
--> Retrieved no components for: com.squareup.moshi:moshi-kotlin:1.14.0
--> Retrieved no components for: com.squareup.okhttp3:logging-interceptor:4.10.0
--> Retrieved no components for: com.squareup.okhttp3:okhttp:4.10.0
--> Retrieved no components for: com.squareup.okhttp3:okhttp-urlconnection:4.10.0
--> Retrieved no components for: com.squareup.okio:okio-jvm:3.0.0
--> Retrieved no components for: com.squareup.picasso:picasso:2.5.2
--> Retrieved no components for: com.squareup.retrofit2:adapter-rxjava:2.9.0
--> Retrieved no components for: com.squareup.retrofit2:converter-gson:2.9.0
--> Retrieved no components for: com.squareup.retrofit2:converter-moshi:2.9.0
--> Retrieved no components for: com.squareup.retrofit2:retrofit:2.9.0
--> Retrieved no components for: com.theartofdev.edmodo:android-image-cropper:2.8.0
--> Retrieved no components for: com.yanzhenjie:album:2.1.3
--> Retrieved no components for: com.yanzhenjie:mediascanner:1.0.3
--> Retrieved no components for: commons-codec:commons-codec:1.16.0
--> Retrieved no components for: commons-logging:commons-logging:1.2
--> Retrieved no components for: de.hdodenhof:circleimageview:2.1.0
--> Retrieved no components for: io.insert-koin:koin-android:3.4.2
--> Retrieved no components for: io.insert-koin:koin-android-compat:3.4.2
--> Retrieved no components for: io.insert-koin:koin-core-jvm:3.4.2
--> Retrieved no components for: io.reactivex.rxjava2:rxandroid:2.1.1
--> Retrieved no components for: io.reactivex.rxjava3:rxandroid:3.0.0
--> Retrieved no components for: io.reactivex.rxjava3:rxjava:3.0.13
--> Retrieved no components for: io.reactivex.rxjava3:rxkotlin:3.0.1
--> Retrieved no components for: io.reactivex:rxandroid:1.2.1
--> Retrieved no components for: io.reactivex:rxjava:1.3.8
--> Retrieved no components for: io.reactivex:rxjava-debug:1.0.3
--> Retrieved no components for: io.realm:android-adapters:2.1.1
--> Retrieved no components for: io.realm:realm-android-library:10.14.0-transformer-api
--> Retrieved no components for: io.realm:realm-annotations:10.14.0-transformer-api
--> Retrieved no components for: javax.inject:javax.inject:1
--> Retrieved no components for: joda-time:joda-time:2.12.0
--> Retrieved no components for: net.zetetic:android-database-sqlcipher:4.5.0
--> Retrieved no components for: org.apache.httpcomponents:httpclient:4.5.4
--> Retrieved no components for: org.apache.httpcomponents:httpcore:4.4.7
--> Retrieved no components for: org.apache.httpcomponents:httpmime:4.5.4
--> Retrieved no components for: org.conscrypt:conscrypt-android:2.5.1
--> Retrieved no components for: org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5
--> Retrieved no components for: org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.4.32
--> Retrieved no components for: org.jetbrains.kotlin:kotlin-bom:1.8.22
--> Retrieved no components for: org.jetbrains.kotlin:kotlin-reflect:1.9.0
--> Retrieved no components for: org.jetbrains.kotlin:kotlin-stdlib:1.9.10
--> Retrieved no components for: org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10
--> Retrieved no components for: org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10
--> Retrieved no components for: org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10
--> Retrieved no components for: org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4
--> Retrieved no components for: org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.6.4
--> Retrieved no components for: org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4
--> Retrieved no components for: org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.6.4
--> Retrieved no components for: org.jetbrains.kotlinx:kotlinx-serialization-bom:1.6.0
--> Retrieved no components for: org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.6.0
--> Retrieved no components for: org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.6.0
--> Retrieved no components for: org.jetbrains:annotations:20.1.0
--> Retrieved no components for: org.mongodb:bson:3.12.1
--> Retrieved no components for: org.reactivestreams:reactive-streams:1.0.3
--> Retrieved no components for: ru.gildor.coroutines:kotlin-coroutines-okhttp:1.0
```

**Comment by mikepenz** [comment] 2023-10-10 06:29
@tateisu any other changes beside this one? e.g. order of the plugins or such?

**Comment by tateisu** [comment] 2023-10-10 06:40
Migrating to build.gradle.kts usually have a lot of changes, so it's hard to determine what's affected. 
Do you have any recommendations on what order the plugins should be applied?

**Comment by mikepenz** [comment] 2023-10-10 06:41
I'd suggest it's best to apply the plugin last: https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L5 (after the android plugin)

**Comment by tateisu** [comment] 2023-10-10 06:50
thanks. my `app/build.gradle`  is:
```
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.kapt")
    id("com.github.triplet.play") version "3.7.0"
    id("com.google.devtools.ksp")
    id("com.google.firebase.crashlytics")
    id("com.google.gms.google-services")
    id("androidx.navigation.safeargs.kotlin")
    id("realm-android")
    id("com.mikepenz.aboutlibraries.plugin")
}
```

**Comment by mikepenz** [comment] 2024-01-06 08:38
I recently created a new private project which also uses `build.gradle.kts` files, but doesn't show the problem. 
Did you resolve the problem? Or can you maybe reproduce it in the sample app? 

Sorry for the delayed response

**Comment by Nyabsi** [comment] 2024-01-22 08:15
Hey, I would like to report having the exact same issue.

**Comment by mikepenz** [comment] 2024-01-22 08:27
@Nyabsi can you please provide more details how the material3 lib conflicts with the `compose-m3` lib?

**Comment by Nyabsi** [comment] 2024-01-22 08:46
Yes, sure. 

I am not too sure on the specifics but for some reason when I include these following libraries:

```
implementation("com.mikepenz:aboutlibraries-core:10.10.0")
implementation("com.mikepenz:aboutlibraries-compose-m3:10.10.0")
implementation("androidx.compose.material3:material3-android:1.2.0-beta02")
```

It will work just fine without

`implementation("androidx.compose.material3:material3-android:1.2.0-beta02")` because `implementation("com.mikepenz:aboutlibraries-compose-m3:10.10.0")` some how already includes the compose components for `material3-android`

remvoing

```
implementation("androidx.compose.material3:material3-android:1.2.0-beta02")
```

will solve the conflict, but it also means I am stuck on older material3 components on my project.

**Comment by mikepenz** [comment] 2024-01-22 08:50
Oh. I think It might be because the `-m3` dependency have the compose-multiplatform variant.

Can you try to do: 
```
implementation("com.mikepenz:aboutlibraries-compose-m3:10.10.0@aar")
```
or 
```
implementation("com.mikepenz:aboutlibraries-compose-m3-android:10.10.0@aar")
```

To force load it without transitive dependencies

**Comment by Nyabsi** [comment] 2024-01-22 08:50
Yes, I can test that shortly. I'll get back asap.

**Comment by Nyabsi** [comment] 2024-01-22 09:12
The proposed workaround works. I can now use `com.mikepenz:aboutlibraries-compose-m3-android` by adding `@aar` at the end of the implementation.

Thank you!

**Comment by mikepenz** [comment] 2024-01-22 10:45
@Nyabsi the immutable collections dependency is a transitive depdendency of the `compose` modules. So as you only include the singular dependency for compose (but none of the dependent ones) you will have to add this dependency yourself. 

you can see what `compose-m3` normally depends on:
https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries-compose-m3/build.gradle.kts#L103

So you want to add kotlinx.collections.immutable:
https://github.com/Kotlin/kotlinx.collections.immutable?tab=readme-ov-file#using-in-your-projects

**Comment by Nyabsi** [comment] 2024-01-22 10:59
@mikepenz that solves the issue for me, thank you. I hope this may also help the original author of this issue to solve their problem, unless it is already solved.

**Comment by mikepenz** [comment] 2024-01-25 13:24
For the original author, please report back if this is still happening, and if it may be the same problem as @Nyabsi mentioned. 

Closing for the time being.

**Closed by mikepenz** 2024-01-25 13:24 UTC

**Comment by HikmatTatariAllone** [comment] 2024-03-27 17:24
Hey,

I use `build.gradles` files and I get the same logs as the original author. 
In my case, the issue arises if I update the AGP and Gradle versions. 

- `agp_version = '8.1.4'` with Gradle version `8.0.2`:  works without any issues.
- `agp_version = '8.2.0'` with Gradle version `8.2`, (or later versions): issue arises.

**Comment by mikepenz** [comment] 2024-03-27 20:55
do you have the configuration cache enabled @HikmatTatariAllone ?

**Comment by keta1** [comment] 2025-04-06 11:31
![Image](https://github.com/user-attachments/assets/276e9372-4a25-4081-b52b-b0ea43233e82)

After updating to 12.0.0-b02, the same issue reappeared

**Comment by mikepenz** [comment] 2025-04-06 11:35
@keta1 likely the configuration cache again :/ Spent quite a lot of time on the latest release to test this, and things looked fine and more stable than before. but I guess there might be more edge cases at times.

you also updated the plugin?

**Comment by keta1** [comment] 2025-04-06 11:38
> [@keta1](https://github.com/keta1) likely the configuration cache again :/ Spent quite a lot of time on the latest release to test this, and things looked fine and more stable than before. but I guess there might be more edge cases at times.
> 
> you also updated the plugin?

I'm running gradle sync in a [sample of markdown renderer ](https://github.com/mikepenz/multiplatform-markdown-renderer)and this issue is what happens

**Comment by mikepenz** [comment] 2025-04-06 11:46
@keta1 oh looking more on it. this is not the same issue as the original ticket. 

the components it can't resolve are not actual modules that were published. `main` / `shared` are local sample app modules not published. and the `-metadata` ones are neither. 

Can you please open a new issue. I might need to lower the log level or see if we can identify such dependencies in another way.
